export const excludedLookupValues = ['WeighingCategory'];

// TODO: Remove after testing
// export const lookupDataValues: LookupItem[] = [
//   {
//     LookupId: '1',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'HEDIS',
//   },
//   {
//     LookupId: '2',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'Pharmacy',
//   },
//   {
//     LookupId: '3',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'Operations',
//   },
//   {
//     LookupId: '4',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'HOS',
//   },
//   {
//     LookupId: '5',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'CAHPS',
//   },
//   {
//     LookupId: '6',
//     LookupType: 'MeasureCategory',
//     LookupName: 'Null',
//     LookupValue: 'Improvement',
//   },
//   {
//     LookupId: '7',
//     LookupType: 'SubMeasureCategory',
//     LookupName: 'HEDIS',
//     LookupValue: 'Admin',
//   },
//   {
//     LookupId: '8',
//     LookupType: 'SubMeasureCategory',
//     LookupName: 'HEDIS',
//     LookupValue: 'Hybrid',
//   },
//   {
//     LookupId: '9',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: '1876Cost',
//   },
//   {
//     LookupId: '10',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'CCPw/oSNP',
//   },
//   {
//     LookupId: '11',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'CCPwithSNP',
//   },
//   {
//     LookupId: '12',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'CCPwithOnlyI-SNP',
//   },
//   {
//     LookupId: '14',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'MSA',
//   },
//   {
//     LookupId: '15',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'PDP',
//   },
//   {
//     LookupId: '16',
//     LookupType: 'ContractType',
//     LookupName: 'Null',
//     LookupValue: 'PFFS',
//   },
//   {
//     LookupId: '17',
//     LookupType: 'MeasureType',
//     LookupName: 'Null',
//     LookupValue: 'C',
//   },
//   {
//     LookupId: '18',
//     LookupType: 'MeasureType',
//     LookupName: 'Null',
//     LookupValue: 'D',
//   },
//   {
//     LookupId: '19',
//     LookupType: 'MeasureType',
//     LookupName: 'Null',
//     LookupValue: 'CD',
//   },
//   {
//     LookupId: '20',
//     LookupType: 'WeighingCategory',
//     LookupName: 'Outcomeorintermediateoutcomemeasure',
//     LookupValue: '3',
//   },
//   {
//     LookupId: '21',
//     LookupType: 'WeighingCategory',
//     LookupName: 'Accessorpatientexperience/complaintsmeasure',
//     LookupValue: '4',
//   },
//   {
//     LookupId: '22',
//     LookupType: 'WeighingCategory',
//     LookupName: 'Processmeasure',
//     LookupValue: '1',
//   },
//   {
//     LookupId: '23',
//     LookupType: 'DomainType',
//     LookupName: 'HD1',
//     LookupValue: 'StayingHealthy:Screenings,TestsandVaccines',
//   },
//   {
//     LookupId: '24',
//     LookupType: 'DomainType',
//     LookupName: 'HD2',
//     LookupValue: 'ManagingChronic(LongTerm)Conditions',
//   },
//   {
//     LookupId: '25',
//     LookupType: 'DomainType',
//     LookupName: 'HD3',
//     LookupValue: 'MemberExperiencewithHealthPlan',
//   },
//   {
//     LookupId: '26',
//     LookupType: 'DomainType',
//     LookupName: 'HD4',
//     LookupValue: "MemberComplaintsandChangesintheHealthPlan'sPerformance",
//   },
//   {
//     LookupId: '27',
//     LookupType: 'DomainType',
//     LookupName: 'HD5',
//     LookupValue: 'HealthPlanCustomerService',
//   },
// ];
