export const OUTER_BOX_CONTAINER = {
  color: '#FCFCFC',
  fontWeight: 400,
  fontSize: '14px',
  textTransform: 'none',
  borderRadius: '8px',
  background: '#666A94',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  columnGap: '8px',
  padding: '0px 8px',
  height: '32px',
  minWidth: '240px',
};
